export const periodicTableElements = [
  {
    "Z": 1,
    "Sym.": "H",
    "Element": "Hydrogen",
    "origin": "Big Bang",
    "Group": 1,
    "Period": 1,
    "Block": "s",
    "Atomic weight": 1.008,
    "Density": 0.00008988,
    "Melting point": 14.01,
    "Boiling point": 20.28,
    "Specific heat capacity": 14.304,
    "Electro­negativity": 2.20,
    "Abundance in Earth's crust": 1400,
    "Origin": "Big Bang"
  },
  {
    "Z": 2,
    "Sym.": "He",
    "Element": "Helium",
    "origin": "Big Bang",
    "Group": 18,
    "Period": 1,
    "Block": "s",
    "Atomic weight": 4.0026,
    "Density": 0.0001785,
    "Melting point": null,
    "Boiling point": 4.22,
    "Specific heat capacity": 5.193,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0.008,
    "Origin": "Big Bang"
  },
  {
    "Z": 3,
    "Sym.": "Li",
    "Element": "Lithium",
    "origin": "Big Bang",
    "Group": 1,
    "Period": 2,
    "Block": "s",
    "Atomic weight": 6.94,
    "Density": 0.534,
    "Melting point": 453.65,
    "Boiling point": 1615,
    "Specific heat capacity": 3.582,
    "Electro­negativity": 0.98,
    "Abundance in Earth's crust": 20,
    "Origin": "Big Bang"
  },
  {
    "Z": 4,
    "Sym.": "Be",
    "Element": "Beryllium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 2,
    "Block": "s",
    "Atomic weight": 9.0122,
    "Density": 1.85,
    "Melting point": 1560,
    "Boiling point": 2743,
    "Specific heat capacity": 1.825,
    "Electro­negativity": 1.57,
    "Abundance in Earth's crust": 2.8,
    "Origin": "Stellar"
  },
  {
    "Z": 5,
    "Sym.": "B",
    "Element": "Boron",
    "origin": "Stellar",
    "Group": 13,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 10.81,
    "Density": 2.34,
    "Melting point": 2349,
    "Boiling point": 4200,
    "Specific heat capacity": 1.026,
    "Electro­negativity": 2.04,
    "Abundance in Earth's crust": 10,
    "Origin": "Stellar"
  },
  {
    "Z": 6,
    "Sym.": "C",
    "Element": "Carbon",
    "origin": "Stellar",
    "Group": 14,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 12.011,
    "Density": 2.267,
    "Melting point": 3823,
    "Boiling point": 4300,
    "Specific heat capacity": 0.709,
    "Electro­negativity": 2.55,
    "Abundance in Earth's crust": 200,
    "Origin": "Stellar"
  },
  {
    "Z": 7,
    "Sym.": "N",
    "Element": "Nitrogen",
    "origin": "Stellar",
    "Group": 15,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 14.007,
    "Density": 0.001251,
    "Melting point": 63.15,
    "Boiling point": 77.36,
    "Specific heat capacity": 1.040,
    "Electro­negativity": 3.04,
    "Abundance in Earth's crust": 19,
    "Origin": "Stellar"
  },
  {
    "Z": 8,
    "Sym.": "O",
    "Element": "Oxygen",
    "origin": "Stellar",
    "Group": 16,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 15.999,
    "Density": 0.001429,
    "Melting point": 54.36,
    "Boiling point": 90.188,
    "Specific heat capacity": 0.918,
    "Electro­negativity": 3.44,
    "Abundance in Earth's crust": 460000,
    "Origin": "Stellar"
  },
  {
    "Z": 9,
    "Sym.": "F",
    "Element": "Fluorine",
    "origin": "Stellar",
    "Group": 17,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 18.998,
    "Density": 0.001696,
    "Melting point": 53.48,
    "Boiling point": 85.03,
    "Specific heat capacity": 0.824,
    "Electro­negativity": 3.98,
    "Abundance in Earth's crust": 585,
    "Origin": "Stellar"
  },
  {
    "Z": 10,
    "Sym.": "Ne",
    "Element": "Neon",
    "origin": "Stellar",
    "Group": 18,
    "Period": 2,
    "Block": "p",
    "Atomic weight": 20.180,
    "Density": 0.0008999,
    "Melting point": 24.56,
    "Boiling point": 27.07,
    "Specific heat capacity": 1.030,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0.005,
    "Origin": "Stellar"
  },
  {
    "Z": 11,
    "Sym.": "Na",
    "Element": "Sodium",
    "origin": "Stellar",
    "Group": 1,
    "Period": 3,
    "Block": "s",
    "Atomic weight": 22.990,
    "Density": 0.968,
    "Melting point": 370.944,
    "Boiling point": 1156,
    "Specific heat capacity": 1.230,
    "Electro­negativity": 0.93,
    "Abundance in Earth's crust": 23000,
    "Origin": "Stellar"
  },
  {
    "Z": 12,
    "Sym.": "Mg",
    "Element": "Magnesium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 3,
    "Block": "s",
    "Atomic weight": 24.305,
    "Density": 1.738,
    "Melting point": 923,
    "Boiling point": 1363,
    "Specific heat capacity": 1.023,
    "Electro­negativity": 1.31,
    "Abundance in Earth's crust": 23000,
    "Origin": "Stellar"
  },
  {
    "Z": 13,
    "Sym.": "Al",
    "Element": "Aluminium",
    "origin": "Stellar",
    "Group": 13,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 26.982,
    "Density": 2.70,
    "Melting point": 933.47,
    "Boiling point": 2743,
    "Specific heat capacity": 0.897,
    "Electro­negativity": 1.61,
    "Abundance in Earth's crust": 82000,
    "Origin": "Stellar"
  },
  {
    "Z": 14,
    "Sym.": "Si",
    "Element": "Silicon",
    "origin": "Stellar",
    "Group": 14,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 28.085,
    "Density": 2.329,
    "Melting point": 1687,
    "Boiling point": 3538,
    "Specific heat capacity": 0.705,
    "Electro­negativity": 1.90,
    "Abundance in Earth's crust": 280000,
    "Origin": "Stellar"
  },
  {
    "Z": 15,
    "Sym.": "P",
    "Element": "Phosphorus",
    "origin": "Stellar",
    "Group": 15,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 30.974,
    "Density": 1.823,
    "Melting point": 317.3,
    "Boiling point": 550,
    "Specific heat capacity": 0.769,
    "Electro­negativity": 2.19,
    "Abundance in Earth's crust": 1050,
    "Origin": "Stellar"
  },
  {
    "Z": 16,
    "Sym.": "S",
    "Element": "Sulfur",
    "origin": "Stellar",
    "Group": 16,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 32.06,
    "Density": 2.07,
    "Melting point": 388.36,
    "Boiling point": 717.8,
    "Specific heat capacity": 0.710,
    "Electro­negativity": 2.58,
    "Abundance in Earth's crust": 350,
    "Origin": "Stellar"
  },
  {
    "Z": 17,
    "Sym.": "Cl",
    "Element": "Chlorine",
    "origin": "Stellar",
    "Group": 17,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 35.45,
    "Density": 0.003214,
    "Melting point": 171.6,
    "Boiling point": 239.11,
    "Specific heat capacity": 0.480,
    "Electro­negativity": 3.16,
    "Abundance in Earth's crust": 130,
    "Origin": "Stellar"
  },
  {
    "Z": 18,
    "Sym.": "Ar",
    "Element": "Argon",
    "origin": "Stellar",
    "Group": 18,
    "Period": 3,
    "Block": "p",
    "Atomic weight": 39.948,
    "Density": 0.001784,
    "Melting point": 83.80,
    "Boiling point": 87.30,
    "Specific heat capacity": 0.520,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 3.5,
    "Origin": "Stellar"
  },
  {
    "Z": 19,
    "Sym.": "K",
    "Element": "Potassium",
    "origin": "Stellar",
    "Group": 1,
    "Period": 4,
    "Block": "s",
    "Atomic weight": 39.098,
    "Density": 0.856,
    "Melting point": 336.53,
    "Boiling point": 1032,
    "Specific heat capacity": 0.757,
    "Electro­negativity": 0.82,
    "Abundance in Earth's crust": 17000,
    "Origin": "Stellar"
  },
  {
    "Z": 20,
    "Sym.": "Ca",
    "Element": "Calcium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 4,
    "Block": "s",
    "Atomic weight": 40.078,
    "Density": 1.55,
    "Melting point": 1115,
    "Boiling point": 1757,
    "Specific heat capacity": 0.631,
    "Electro­negativity": 1.00,
    "Abundance in Earth's crust": 41000,
    "Origin": "Stellar"
  },
  {
    "Z": 21,
    "Sym.": "Sc",
    "Element": "Scandium",
    "origin": "Stellar",
    "Group": 3,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 44.956,
    "Density": 2.985,
    "Melting point": 1814,
    "Boiling point": 3109,
    "Specific heat capacity": 0.568,
    "Electro­negativity": 1.36,
    "Abundance in Earth's crust": 22,
    "Origin": "Stellar"
  },
  {
    "Z": 22,
    "Sym.": "Ti",
    "Element": "Titanium",
    "origin": "Stellar",
    "Group": 4,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 47.867,
    "Density": 4.506,
    "Melting point": 1941,
    "Boiling point": 3560,
    "Specific heat capacity": 0.522,
    "Electro­negativity": 1.54,
    "Abundance in Earth's crust": 5650,
    "Origin": "Stellar"
  },
  {
    "Z": 23,
    "Sym.": "V",
    "Element": "Vanadium",
    "origin": "Stellar",
    "Group": 5,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 50.942,
    "Density": 6.11,
    "Melting point": 2183,
    "Boiling point": 3680,
    "Specific heat capacity": 0.489,
    "Electro­negativity": 1.63,
    "Abundance in Earth's crust": 49,
    "Origin": "Stellar"
  },
  {
    "Z": 24,
    "Sym.": "Cr",
    "Element": "Chromium",
    "origin": "Stellar",
    "Group": 6,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 51.996,
    "Density": 7.15,
    "Melting point": 2180,
    "Boiling point": 2944,
    "Specific heat capacity": 0.449,
    "Electro­negativity": 1.66,
    "Abundance in Earth's crust": 102,
    "Origin": "Stellar"
  },
  {
    "Z": 25,
    "Sym.": "Mn",
    "Element": "Manganese",
    "origin": "Stellar",
    "Group": 7,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 54.938,
    "Density": 7.21,
    "Melting point": 1519,
    "Boiling point": 2334,
    "Specific heat capacity": 0.479,
    "Electro­negativity": 1.55,
    "Abundance in Earth's crust": 950,
    "Origin": "Stellar"
  },
  {
    "Z": 26,
    "Sym.": "Fe",
    "Element": "Iron",
    "origin": "Stellar",
    "Group": 8,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 55.845,
    "Density": 7.874,
    "Melting point": 1811,
    "Boiling point": 3134,
    "Specific heat capacity": 0.449,
    "Electro­negativity": 1.83,
    "Abundance in Earth's crust": 50000,
    "Origin": "Stellar"
  },
  {
    "Z": 27,
    "Sym.": "Co",
    "Element": "Cobalt",
    "origin": "Stellar",
    "Group": 9,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 58.933,
    "Density": 8.90,
    "Melting point": 1768,
    "Boiling point": 3200,
    "Specific heat capacity": 0.421,
    "Electro­negativity": 1.88,
    "Abundance in Earth's crust": 25,
    "Origin": "Stellar"
  },
  {
    "Z": 28,
    "Sym.": "Ni",
    "Element": "Nickel",
    "origin": "Stellar",
    "Group": 10,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 58.693,
    "Density": 8.908,
    "Melting point": 1728,
    "Boiling point": 3186,
    "Specific heat capacity": 0.444,
    "Electro­negativity": 1.91,
    "Abundance in Earth's crust": 84,
    "Origin": "Stellar"
  },
  {
    "Z": 29,
    "Sym.": "Cu",
    "Element": "Copper",
    "origin": "Stellar",
    "Group": 11,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 63.546,
    "Density": 8.96,
    "Melting point": 1357.77,
    "Boiling point": 2835,
    "Specific heat capacity": 0.385,
    "Electro­negativity": 1.90,
    "Abundance in Earth's crust": 60,
    "Origin": "Stellar"
  },
  {
    "Z": 30,
    "Sym.": "Zn",
    "Element": "Zinc",
    "origin": "Stellar",
    "Group": 12,
    "Period": 4,
    "Block": "d",
    "Atomic weight": 65.38,
    "Density": 7.14,
    "Melting point": 692.68,
    "Boiling point": 1180,
    "Specific heat capacity": 0.388,
    "Electro­negativity": 1.65,
    "Abundance in Earth's crust": 70,
    "Origin": "Stellar"
  },
  {
    "Z": 31,
    "Sym.": "Ga",
    "Element": "Gallium",
    "origin": "Stellar",
    "Group": 13,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 69.723,
    "Density": 5.91,
    "Melting point": 302.9146,
    "Boiling point": 2477,
    "Specific heat capacity": 0.371,
    "Electro­negativity": 1.81,
    "Abundance in Earth's crust": 19,
    "Origin": "Stellar"
  },
  {
    "Z": 32,
    "Sym.": "Ge",
    "Element": "Germanium",
    "origin": "Stellar",
    "Group": 14,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 72.630,
    "Density": 5.323,
    "Melting point": 1211.4,
    "Boiling point": 3106,
    "Specific heat capacity": 0.320,
    "Electro­negativity": 2.01,
    "Abundance in Earth's crust": 1.5,
    "Origin": "Stellar"
  },
  {
    "Z": 33,
    "Sym.": "As",
    "Element": "Arsenic",
    "origin": "Stellar",
    "Group": 15,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 74.922,
    "Density": 5.727,
    "Melting point": 1090,
    "Boiling point": 1090,
    "Specific heat capacity": 0.328,
    "Electro­negativity": 2.18,
    "Abundance in Earth's crust": 1.8,
    "Origin": "Stellar"
  },
  {
    "Z": 34,
    "Sym.": "Se",
    "Element": "Selenium",
    "origin": "Stellar",
    "Group": 16,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 78.971,
    "Density": 4.81,
    "Melting point": 494,
    "Boiling point": 958,
    "Specific heat capacity": 0.321,
    "Electro­negativity": 2.55,
    "Abundance in Earth's crust": 0.05,
    "Origin": "Stellar"
  },
  {
    "Z": 35,
    "Sym.": "Br",
    "Element": "Bromine",
    "origin": "Stellar",
    "Group": 17,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 79.904,
    "Density": 3.122,
    "Melting point": 265.8,
    "Boiling point": 332.0,
    "Specific heat capacity": 0.474,
    "Electro­negativity": 2.96,
    "Abundance in Earth's crust": 2.4,
    "Origin": "Stellar"
  },
  {
    "Z": 36,
    "Sym.": "Kr",
    "Element": "Krypton",
    "origin": "Stellar",
    "Group": 18,
    "Period": 4,
    "Block": "p",
    "Atomic weight": 83.798,
    "Density": 0.003733,
    "Melting point": 115.78,
    "Boiling point": 119.93,
    "Specific heat capacity": 0.248,
    "Electro­negativity": null,
    "Abundance in Earth's crust": null,
    "Origin": "Stellar"
  },
  {
    "Z": 37,
    "Sym.": "Rb",
    "Element": "Rubidium",
    "origin": "Stellar",
    "Group": 1,
    "Period": 5,
    "Block": "s",
    "Atomic weight": 85.468,
    "Density": 1.532,
    "Melting point": 312.46,
    "Boiling point": 961,
    "Specific heat capacity": 0.363,
    "Electro­negativity": 0.82,
    "Abundance in Earth's crust": 90,
    "Origin": "Stellar"
  },
  {
    "Z": 38,
    "Sym.": "Sr",
    "Element": "Strontium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 5,
    "Block": "s",
    "Atomic weight": 87.62,
    "Density": 2.63,
    "Melting point": 1050,
    "Boiling point": 1650,
    "Specific heat capacity": 0.301,
    "Electro­negativity": 0.95,
    "Abundance in Earth's crust": 370,
    "Origin": "Stellar"
  },
  {
    "Z": 39,
    "Sym.": "Y",
    "Element": "Yttrium",
    "origin": "Stellar",
    "Group": 3,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 88.906,
    "Density": 4.47,
    "Melting point": 1799,
    "Boiling point": 3609,
    "Specific heat capacity": 0.285,
    "Electro­negativity": 1.22,
    "Abundance in Earth's crust": 33,
    "Origin": "Stellar"
  },
  {
    "Z": 40,
    "Sym.": "Zr",
    "Element": "Zirconium",
    "origin": "Stellar",
    "Group": 4,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 91.224,
    "Density": 6.52,
    "Melting point": 2128,
    "Boiling point": 4650,
    "Specific heat capacity": 0.278,
    "Electro­negativity": 1.33,
    "Abundance in Earth's crust": 130,
    "Origin": "Stellar"
  },
  {
    "Z": 41,
    "Sym.": "Nb",
    "Element": "Niobium",
    "origin": "Stellar",
    "Group": 5,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 92.906,
    "Density": 8.57,
    "Melting point": 2750,
    "Boiling point": 5017,
    "Specific heat capacity": 0.265,
    "Electro­negativity": 1.6,
    "Abundance in Earth's crust": 20,
    "Origin": "Stellar"
  },
  {
    "Z": 42,
    "Sym.": "Mo",
    "Element": "Molybdenum",
    "origin": "Stellar",
    "Group": 6,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 95.95,
    "Density": 10.28,
    "Melting point": 2896,
    "Boiling point": 4912,
    "Specific heat capacity": 0.251,
    "Electro­negativity": 2.16,
    "Abundance in Earth's crust": 1.2,
    "Origin": "Stellar"
  },
  {
    "Z": 43,
    "Sym.": "Tc",
    "Element": "Technetium",
    "origin": "Stellar",
    "Group": 7,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 98,
    "Density": 11.5,
    "Melting point": 2430,
    "Boiling point": 4538,
    "Specific heat capacity": null,
    "Electro­negativity": 1.9,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 44,
    "Sym.": "Ru",
    "Element": "Ruthenium",
    "origin": "Stellar",
    "Group": 8,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 101.07,
    "Density": 12.37,
    "Melting point": 2607,
    "Boiling point": 4423,
    "Specific heat capacity": 0.238,
    "Electro­negativity": 2.2,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 45,
    "Sym.": "Rh",
    "Element": "Rhodium",
    "origin": "Stellar",
    "Group": 9,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 102.91,
    "Density": 12.41,
    "Melting point": 2237,
    "Boiling point": 3968,
    "Specific heat capacity": 0.243,
    "Electro­negativity": 2.28,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 46,
    "Sym.": "Pd",
    "Element": "Palladium",
    "origin": "Stellar",
    "Group": 10,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 106.42,
    "Density": 12.023,
    "Melting point": 1828.05,
    "Boiling point": 3236,
    "Specific heat capacity": 0.244,
    "Electro­negativity": 2.20,
    "Abundance in Earth's crust": 0.015,
    "Origin": "Stellar"
  },
  {
    "Z": 47,
    "Sym.": "Ag",
    "Element": "Silver",
    "origin": "Stellar",
    "Group": 11,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 107.87,
    "Density": 10.49,
    "Melting point": 1234.93,
    "Boiling point": 2435,
    "Specific heat capacity": 0.235,
    "Electro­negativity": 1.93,
    "Abundance in Earth's crust": 0.075,
    "Origin": "Stellar"
  },
  {
    "Z": 48,
    "Sym.": "Cd",
    "Element": "Cadmium",
    "origin": "Stellar",
    "Group": 12,
    "Period": 5,
    "Block": "d",
    "Atomic weight": 112.41,
    "Density": 8.65,
    "Melting point": 594.22,
    "Boiling point": 1040,
    "Specific heat capacity": 0.232,
    "Electro­negativity": 1.69,
    "Abundance in Earth's crust": 0.15,
    "Origin": "Stellar"
  },
  {
    "Z": 49,
    "Sym.": "In",
    "Element": "Indium",
    "origin": "Stellar",
    "Group": 13,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 114.82,
    "Density": 7.31,
    "Melting point": 429.75,
    "Boiling point": 2345,
    "Specific heat capacity": 0.230,
    "Electro­negativity": 1.78,
    "Abundance in Earth's crust": 0.25,
    "Origin": "Stellar"
  },
  {
    "Z": 50,
    "Sym.": "Sn",
    "Element": "Tin",
    "origin": "Stellar",
    "Group": 14,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 118.71,
    "Density": 7.310,
    "Melting point": 505.08,
    "Boiling point": 2875,
    "Specific heat capacity": 0.228,
    "Electro­negativity": 1.96,
    "Abundance in Earth's crust": 2.3,
    "Origin": "Stellar"
  },
  {
    "Z": 51,
    "Sym.": "Sb",
    "Element": "Antimony",
    "origin": "Stellar",
    "Group": 15,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 121.76,
    "Density": 6.697,
    "Melting point": 903.78,
    "Boiling point": 1908,
    "Specific heat capacity": 0.207,
    "Electro­negativity": 2.05,
    "Abundance in Earth's crust": 0.2,
    "Origin": "Stellar"
  },
  {
    "Z": 52,
    "Sym.": "Te",
    "Element": "Tellurium",
    "origin": "Stellar",
    "Group": 16,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 127.60,
    "Density": 6.24,
    "Melting point": 722.66,
    "Boiling point": 1261,
    "Specific heat capacity": 0.202,
    "Electro­negativity": 2.1,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 53,
    "Sym.": "I",
    "Element": "Iodine",
    "origin": "Stellar",
    "Group": 17,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 126.90,
    "Density": 4.93,
    "Melting point": 386.85,
    "Boiling point": 457.4,
    "Specific heat capacity": 0.214,
    "Electro­negativity": 2.66,
    "Abundance in Earth's crust": 0.45,
    "Origin": "Stellar"
  },
  {
    "Z": 54,
    "Sym.": "Xe",
    "Element": "Xenon",
    "origin": "Stellar",
    "Group": 18,
    "Period": 5,
    "Block": "p",
    "Atomic weight": 131.29,
    "Density": 0.005887,
    "Melting point": 161.4,
    "Boiling point": 165.051,
    "Specific heat capacity": 0.158,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0.00003,
    "Origin": "Stellar"
  },
  {
    "Z": 55,
    "Sym.": "Cs",
    "Element": "Caesium",
    "origin": "Stellar",
    "Group": 1,
    "Period": 6,
    "Block": "s",
    "Atomic weight": 132.91,
    "Density": 1.879,
    "Melting point": 301.59,
    "Boiling point": 944,
    "Specific heat capacity": 0.242,
    "Electro­negativity": 0.79,
    "Abundance in Earth's crust": 3,
    "Origin": "Stellar"
  },
  {
    "Z": 56,
    "Sym.": "Ba",
    "Element": "Barium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 6,
    "Block": "s",
    "Atomic weight": 137.33,
    "Density": 3.51,
    "Melting point": 1000,
    "Boiling point": 2118,
    "Specific heat capacity": 0.204,
    "Electro­negativity": 0.89,
    "Abundance in Earth's crust": 425,
    "Origin": "Stellar"
  },
  {
    "Z": 57,
    "Sym.": "La",
    "Element": "Lanthanum",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 138.91,
    "Density": 6.15,
    "Melting point": 1193,
    "Boiling point": 3737,
    "Specific heat capacity": 0.195,
    "Electro­negativity": 1.10,
    "Abundance in Earth's crust": 39,
    "Origin": "Stellar"
  },
  {
    "Z": 58,
    "Sym.": "Ce",
    "Element": "Cerium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 140.12,
    "Density": 6.77,
    "Melting point": 1068,
    "Boiling point": 3716,
    "Specific heat capacity": 0.192,
    "Electro­negativity": 1.12,
    "Abundance in Earth's crust": 66.5,
    "Origin": "Stellar"
  },
  {
    "Z": 59,
    "Sym.": "Pr",
    "Element": "Praseodymium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 140.91,
    "Density": 6.77,
    "Melting point": 1208,
    "Boiling point": 3793,
    "Specific heat capacity": 0.193,
    "Electro­negativity": 1.13,
    "Abundance in Earth's crust": 9.2,
    "Origin": "Stellar"
  },
  {
    "Z": 60,
    "Sym.": "Nd",
    "Element": "Neodymium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 144.24,
    "Density": 7.01,
    "Melting point": 1297,
    "Boiling point": 3347,
    "Specific heat capacity": 0.190,
    "Electro­negativity": 1.14,
    "Abundance in Earth's crust": 41.5,
    "Origin": "Stellar"
  },
  {
    "Z": 61,
    "Sym.": "Pm",
    "Element": "Promethium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 145,
    "Density": 7.26,
    "Melting point": 1315,
    "Boiling point": 3273,
    "Specific heat capacity": null,
    "Electro­negativity": 1.13,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 62,
    "Sym.": "Sm",
    "Element": "Samarium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 150.36,
    "Density": 7.52,
    "Melting point": 1345,
    "Boiling point": 2067,
    "Specific heat capacity": 0.197,
    "Electro­negativity": 1.17,
    "Abundance in Earth's crust": 7.05,
    "Origin": "Stellar"
  },
  {
    "Z": 63,
    "Sym.": "Eu",
    "Element": "Europium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 151.96,
    "Density": 5.244,
    "Melting point": 1099,
    "Boiling point": 1802,
    "Specific heat capacity": 0.182,
    "Electro­negativity": 1.20,
    "Abundance in Earth's crust": 2,
    "Origin": "Stellar"
  },
  {
    "Z": 64,
    "Sym.": "Gd",
    "Element": "Gadolinium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 157.25,
    "Density": 7.90,
    "Melting point": 1585,
    "Boiling point": 3546,
    "Specific heat capacity": 0.236,
    "Electro­negativity": 1.20,
    "Abundance in Earth's crust": 6.2,
    "Origin": "Stellar"
  },
  {
    "Z": 65,
    "Sym.": "Tb",
    "Element": "Terbium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 158.93,
    "Density": 8.23,
    "Melting point": 1629,
    "Boiling point": 3503,
    "Specific heat capacity": 0.183,
    "Electro­negativity": 1.20,
    "Abundance in Earth's crust": 1.2,
    "Origin": "Stellar"
  },
  {
    "Z": 66,
    "Sym.": "Dy",
    "Element": "Dysprosium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 162.50,
    "Density": 8.54,
    "Melting point": 1680,
    "Boiling point": 2840,
    "Specific heat capacity": 0.170,
    "Electro­negativity": 1.22,
    "Abundance in Earth's crust": 5.2,
    "Origin": "Stellar"
  },
  {
    "Z": 67,
    "Sym.": "Ho",
    "Element": "Holmium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 164.93,
    "Density": 8.80,
    "Melting point": 1747,
    "Boiling point": 2993,
    "Specific heat capacity": 0.165,
    "Electro­negativity": 1.23,
    "Abundance in Earth's crust": 1.3,
    "Origin": "Stellar"
  },
  {
    "Z": 68,
    "Sym.": "Er",
    "Element": "Erbium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 167.26,
    "Density": 9.066,
    "Melting point": 1802,
    "Boiling point": 3141,
    "Specific heat capacity": 0.168,
    "Electro­negativity": 1.24,
    "Abundance in Earth's crust": 3.5,
    "Origin": "Stellar"
  },
  {
    "Z": 69,
    "Sym.": "Tm",
    "Element": "Thulium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 168.93,
    "Density": 9.32,
    "Melting point": 1818,
    "Boiling point": 2223,
    "Specific heat capacity": 0.160,
    "Electro­negativity": 1.25,
    "Abundance in Earth's crust": 0.52,
    "Origin": "Stellar"
  },
  {
    "Z": 70,
    "Sym.": "Yb",
    "Element": "Ytterbium",
    "origin": "Stellar",
    "Group": null,
    "Period": 6,
    "Block": "f",
    "Atomic weight": 173.05,
    "Density": 6.90,
    "Melting point": 1097,
    "Boiling point": 1469,
    "Specific heat capacity": 0.155,
    "Electro­negativity": 1.1,
    "Abundance in Earth's crust": 3.2,
    "Origin": "Stellar"
  },
  {
    "Z": 71,
    "Sym.": "Lu",
    "Element": "Lutetium",
    "origin": "Stellar",
    "Group": 3,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 174.97,
    "Density": 9.84,
    "Melting point": 1925,
    "Boiling point": 3675,
    "Specific heat capacity": 0.154,
    "Electro­negativity": 1.27,
    "Abundance in Earth's crust": 0.8,
    "Origin": "Stellar"
  },
  {
    "Z": 72,
    "Sym.": "Hf",
    "Element": "Hafnium",
    "origin": "Stellar",
    "Group": 4,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 178.49,
    "Density": 13.31,
    "Melting point": 2506,
    "Boiling point": 4876,
    "Specific heat capacity": 0.144,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 3,
    "Origin": "Stellar"
  },
  {
    "Z": 73,
    "Sym.": "Ta",
    "Element": "Tantalum",
    "origin": "Stellar",
    "Group": 5,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 180.95,
    "Density": 16.69,
    "Melting point": 3290,
    "Boiling point": 5731,
    "Specific heat capacity": 0.140,
    "Electro­negativity": 1.5,
    "Abundance in Earth's crust": 2,
    "Origin": "Stellar"
  },
  {
    "Z": 74,
    "Sym.": "W",
    "Element": "Tungsten",
    "origin": "Stellar",
    "Group": 6,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 183.84,
    "Density": 19.25,
    "Melting point": 3695,
    "Boiling point": 5828,
    "Specific heat capacity": 0.132,
    "Electro­negativity": 2.36,
    "Abundance in Earth's crust": 1.3,
    "Origin": "Stellar"
  },
  {
    "Z": 75,
    "Sym.": "Re",
    "Element": "Rhenium",
    "origin": "Stellar",
    "Group": 7,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 186.21,
    "Density": 21.02,
    "Melting point": 3459,
    "Boiling point": 5869,
    "Specific heat capacity": 0.137,
    "Electro­negativity": 1.9,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 76,
    "Sym.": "Os",
    "Element": "Osmium",
    "origin": "Stellar",
    "Group": 8,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 190.23,
    "Density": 22.59,
    "Melting point": 3306,
    "Boiling point": 5285,
    "Specific heat capacity": 0.130,
    "Electro­negativity": 2.2,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 77,
    "Sym.": "Ir",
    "Element": "Iridium",
    "origin": "Stellar",
    "Group": 9,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 192.22,
    "Density": 22.56,
    "Melting point": 2719,
    "Boiling point": 4701,
    "Specific heat capacity": 0.133,
    "Electro­negativity": 2.20,
    "Abundance in Earth's crust": 0.001,
    "Origin": "Stellar"
  },
  {
    "Z": 78,
    "Sym.": "Pt",
    "Element": "Platinum",
    "origin": "Stellar",
    "Group": 10,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 195.08,
    "Density": 21.45,
    "Melting point": 2041.4,
    "Boiling point": 4098,
    "Specific heat capacity": 0.133,
    "Electro­negativity": 2.28,
    "Abundance in Earth's crust": 0.005,
    "Origin": "Stellar"
  },
  {
    "Z": 79,
    "Sym.": "Au",
    "Element": "Gold",
    "origin": "Stellar",
    "Group": 11,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 196.97,
    "Density": 19.30,
    "Melting point": 1337.33,
    "Boiling point": 3243,
    "Specific heat capacity": 0.129,
    "Electro­negativity": 2.54,
    "Abundance in Earth's crust": 0.004,
    "Origin": "Stellar"
  },
  {
    "Z": 80,
    "Sym.": "Hg",
    "Element": "Mercury",
    "origin": "Stellar",
    "Group": 12,
    "Period": 6,
    "Block": "d",
    "Atomic weight": 200.59,
    "Density": 13.534,
    "Melting point": 234.3210,
    "Boiling point": 629.88,
    "Specific heat capacity": 0.140,
    "Electro­negativity": 2.00,
    "Abundance in Earth's crust": 0.008,
    "Origin": "Stellar"
  },
  {
    "Z": 81,
    "Sym.": "Tl",
    "Element": "Thallium",
    "origin": "Stellar",
    "Group": 13,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 204.38,
    "Density": 11.85,
    "Melting point": 577,
    "Boiling point": 1746,
    "Specific heat capacity": 0.129,
    "Electro­negativity": 2.04,
    "Abundance in Earth's crust": 0.85,
    "Origin": "Stellar"
  },
  {
    "Z": 82,
    "Sym.": "Pb",
    "Element": "Lead",
    "origin": "Stellar",
    "Group": 14,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 207.2,
    "Density": 11.34,
    "Melting point": 600.61,
    "Boiling point": 2022,
    "Specific heat capacity": 0.128,
    "Electro­negativity": 2.33,
    "Abundance in Earth's crust": 14,
    "Origin": "Stellar"
  },
  {
    "Z": 83,
    "Sym.": "Bi",
    "Element": "Bismuth",
    "origin": "Stellar",
    "Group": 15,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 208.98,
    "Density": 9.78,
    "Melting point": 544.7,
    "Boiling point": 1837,
    "Specific heat capacity": 0.123,
    "Electro­negativity": 2.02,
    "Abundance in Earth's crust": 0.009,
    "Origin": "Stellar"
  },
  {
    "Z": 84,
    "Sym.": "Po",
    "Element": "Polonium",
    "origin": "Stellar",
    "Group": 16,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 209,
    "Density": 9.32,
    "Melting point": 527,
    "Boiling point": 1235,
    "Specific heat capacity": null,
    "Electro­negativity": 2.0,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 85,
    "Sym.": "At",
    "Element": "Astatine",
    "origin": "Stellar",
    "Group": 17,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 210,
    "Density": null,
    "Melting point": 575,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": 2.2,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 86,
    "Sym.": "Rn",
    "Element": "Radon",
    "origin": "Stellar",
    "Group": 18,
    "Period": 6,
    "Block": "p",
    "Atomic weight": 222,
    "Density": 0.00973,
    "Melting point": 202,
    "Boiling point": 211.3,
    "Specific heat capacity": 0.094,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 87,
    "Sym.": "Fr",
    "Element": "Francium",
    "origin": "Stellar",
    "Group": 1,
    "Period": 7,
    "Block": "s",
    "Atomic weight": 223,
    "Density": null,
    "Melting point": 300,
    "Boiling point": 950,
    "Specific heat capacity": null,
    "Electro­negativity": 0.7,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 88,
    "Sym.": "Ra",
    "Element": "Radium",
    "origin": "Stellar",
    "Group": 2,
    "Period": 7,
    "Block": "s",
    "Atomic weight": 226,
    "Density": 5.5,
    "Melting point": 973,
    "Boiling point": 2010,
    "Specific heat capacity": null,
    "Electro­negativity": 0.9,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 89,
    "Sym.": "Ac",
    "Element": "Actinium",
    "origin": "Stellar",
    "Group": 3,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 227,
    "Density": 10.07,
    "Melting point": 1323,
    "Boiling point": 3473,
    "Specific heat capacity": null,
    "Electro­negativity": 1.1,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 90,
    "Sym.": "Th",
    "Element": "Thorium",
    "origin": "Stellar",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 232.04,
    "Density": 11.7,
    "Melting point": 2023,
    "Boiling point": 5061,
    "Specific heat capacity": 0.113,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 9.6,
    "Origin": "Stellar"
  },
  {
    "Z": 91,
    "Sym.": "Pa",
    "Element": "Protactinium",
    "origin": "Stellar",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 231.04,
    "Density": 15.37,
    "Melting point": 1841,
    "Boiling point": 4300,
    "Specific heat capacity": null,
    "Electro­negativity": 1.5,
    "Abundance in Earth's crust": 0,
    "Origin": "Stellar"
  },
  {
    "Z": 92,
    "Sym.": "U",
    "Element": "Uranium",
    "origin": "Stellar",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 238.03,
    "Density": 19.05,
    "Melting point": 1405.3,
    "Boiling point": 4404,
    "Specific heat capacity": 0.116,
    "Electro­negativity": 1.38,
    "Abundance in Earth's crust": 1.8,
    "Origin": "Stellar"
  },
  {
    "Z": 93,
    "Sym.": "Np",
    "Element": "Neptunium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 237,
    "Density": 20.45,
    "Melting point": 912,
    "Boiling point": 4273,
    "Specific heat capacity": null,
    "Electro­negativity": 1.36,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 94,
    "Sym.": "Pu",
    "Element": "Plutonium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 244,
    "Density": 19.816,
    "Melting point": 912.5,
    "Boiling point": 3501,
    "Specific heat capacity": null,
    "Electro­negativity": 1.28,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 95,
    "Sym.": "Am",
    "Element": "Americium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 243,
    "Density": 12,
    "Melting point": 1449,
    "Boiling point": 2880,
    "Specific heat capacity": null,
    "Electro­negativity": 1.13,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 96,
    "Sym.": "Cm",
    "Element": "Curium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 247,
    "Density": 13.51,
    "Melting point": 1613,
    "Boiling point": 3383,
    "Specific heat capacity": null,
    "Electro­negativity": 1.28,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 97,
    "Sym.": "Bk",
    "Element": "Berkelium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 247,
    "Density": 14.78,
    "Melting point": 1259,
    "Boiling point": 983,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 98,
    "Sym.": "Cf",
    "Element": "Californium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 251,
    "Density": 15.1,
    "Melting point": 1173,
    "Boiling point": 1743,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 99,
    "Sym.": "Es",
    "Element": "Einsteinium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 252,
    "Density": 8.84,
    "Melting point": 1133,
    "Boiling point": 1269,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 100,
    "Sym.": "Fm",
    "Element": "Fermium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 257,
    "Density": null,
    "Melting point": 1800,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 101,
    "Sym.": "Md",
    "Element": "Mendelevium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 258,
    "Density": null,
    "Melting point": 1100,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 102,
    "Sym.": "No",
    "Element": "Nobelium",
    "origin": "Man-made",
    "Group": null,
    "Period": 7,
    "Block": "f",
    "Atomic weight": 259,
    "Density": null,
    "Melting point": 1100,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 103,
    "Sym.": "Lr",
    "Element": "Lawrencium",
    "origin": "Man-made",
    "Group": 3,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 262,
    "Density": null,
    "Melting point": 1900,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": 1.3,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 104,
    "Sym.": "Rf",
    "Element": "Rutherfordium",
    "origin": "Man-made",
    "Group": 4,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 267,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 105,
    "Sym.": "Db",
    "Element": "Dubnium",
    "origin": "Man-made",
    "Group": 5,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 268,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 106,
    "Sym.": "Sg",
    "Element": "Seaborgium",
    "origin": "Man-made",
    "Group": 6,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 269,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 107,
    "Sym.": "Bh",
    "Element": "Bohrium",
    "origin": "Man-made",
    "Group": 7,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 270,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 108,
    "Sym.": "Hs",
    "Element": "Hassium",
    "origin": "Man-made",
    "Group": 8,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 270,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 109,
    "Sym.": "Mt",
    "Element": "Meitnerium",
    "origin": "Man-made",
    "Group": 9,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 276,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 110,
    "Sym.": "Ds",
    "Element": "Darmstadtium",
    "origin": "Man-made",
    "Group": 10,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 281,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 111,
    "Sym.": "Rg",
    "Element": "Roentgenium",
    "origin": "Man-made",
    "Group": 11,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 280,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 112,
    "Sym.": "Cn",
    "Element": "Copernicium",
    "origin": "Man-made",
    "Group": 12,
    "Period": 7,
    "Block": "d",
    "Atomic weight": 285,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 113,
    "Sym.": "Nh",
    "Element": "Nihonium",
    "origin": "Man-made",
    "Group": 13,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 286,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 114,
    "Sym.": "Fl",
    "Element": "Flerovium",
    "origin": "Man-made",
    "Group": 14,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 289,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 115,
    "Sym.": "Mc",
    "Element": "Moscovium",
    "origin": "Man-made",
    "Group": 15,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 290,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 116,
    "Sym.": "Lv",
    "Element": "Livermorium",
    "origin": "Man-made",
    "Group": 16,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 293,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 117,
    "Sym.": "Ts",
    "Element": "Tennessine",
    "origin": "Man-made",
    "Group": 17,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 294,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  },
  {
    "Z": 118,
    "Sym.": "Og",
    "Element": "Oganesson",
    "origin": "Man-made",
    "Group": 18,
    "Period": 7,
    "Block": "p",
    "Atomic weight": 294,
    "Density": null,
    "Melting point": null,
    "Boiling point": null,
    "Specific heat capacity": null,
    "Electro­negativity": null,
    "Abundance in Earth's crust": 0,
    "Origin": "Man-made"
  }
];

export function getElementName(atomicNumber) {
  const element = periodicTableElements.find(e => e.Z === atomicNumber);
  return element ? element["Sym."] : 'Unknown';
};
